### ISSUE TITLE
Decrease stroke around Level 1 block

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/area-model-multiplication#11]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1032, the outline around the block in Level 1 is thicker than the other blocks. 
@amanda-phet said this is something she would normally fix. 

**Visuals**
<img width="592" alt="Screenshot 2024-01-26 at 1 59 26 PM" src="https://github.com/phetsims/area-model-multiplication/assets/87318828/0bd525dc-bb46-4318-9f75-b8d0ed70ac81">

**Comment by Nancy-Salpepi** [comment]
Seen in the Asia, USA and Oceania character sets (same image is used in all 3).

**Comment by amanda-phet** [comment]
New asset uploaded. Over to @Luisav1

**Comment by Luisav1** [comment]
The artwork is integrated and it's looking good!

**Comment by Luisav1** [comment]
Closing since there's no more work here.
