### ISSUE TITLE
Game level banner size is too small

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/area-model-multiplication#13]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1042 and https://github.com/phetsims/qa/issues/1041 the banner size is smaller in the rc version than in published, leaving very little space around the Start Over button. 

**Visuals**
<img width="1296" alt="Screenshot 2024-02-17 at 2 06 57 PM" src="https://github.com/phetsims/area-model-multiplication/assets/87318828/be9a9e2d-8694-40a8-b3c9-b7ed5e32d20d">

<img width="550" alt="Screenshot 2024-02-19 at 12 33 00 PM" src="https://github.com/phetsims/area-model-multiplication/assets/87318828/3a2c8ff8-dbf0-43a3-a44b-fd0e260723ec">

**Comment by amanda-phet** [comment]
@Luisav1 do you know why this banner changed its size?

**Comment by Luisav1** [comment]
I'm not sure why this banner changed size. I looked into other sims that use this bar and this bar in the AM suite is the only one that shrunk. In looking into it, it seems to have shrunk before the region and culture work was done so I added a fix by setting the yMargin to match the published version.

**Comment by KatieWoe** [comment]
Looks good in rc.2
