### ISSUE TITLE
Update Credits for 1.3 release

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/area-model-multiplication#15]
@Luisav1 don't forget to add yourself to the credits 🙂.
Also please update QA credits to include: Jaron Droder, Clifford Hardin and Nancy Salpepi

Tagging https://github.com/phetsims/qa/issues/1042

**Comment by KatieWoe** [comment]
QA credits should also include these on https://github.com/phetsims/qa/issues/1041

**Comment by Luisav1** [comment]
Thanks for catching that, almost forgot! Updated the credits in AMA and AMM above.

**Comment by KatieWoe** [comment]
Looks good in rc.2
