### ISSUE TITLE
Convert to new Region and Culture approach

### ISSUE THREAD

**Issue by Luisav1** [phetsims/area-model-multiplication#16]
For https://github.com/phetsims/joist/issues/958 to use localizedImageProperty in Area Model Multiplication and Area Model Algebra.

**Comment by Luisav1** [comment]
I'm unsure whether to use generic or specific names for image files. Initially, I opted for `GameHomeScreenIcon` and removed the `Variables` or `Generic` prefix to generalize, since they're utilized within their own AMA and AMM sims. However, considering their usage within `area-model-common` alongside specific elements like `VariablesScreen` or `GenericScreen`, I'm unsure about the appropriate naming convention. @pixelzoom Could you provide guidance?

**Comment by pixelzoom** [comment]
> I'm unsure whether to use generic or specific names for image files. ... @pixelzoom Could you provide guidance?

Wow.  The classing naming (and documentation) in area-model-common sure is confusing.  There are bigger problems here than the image filenames. So I recommend that you just use the existing image filenames, and not try to sort out the naming problem.

I wasn't sure if the R&C conversion was ready for review yet, so I didn't take a look. Feel free to assign back to me for review when you're done.

**Comment by pixelzoom** [comment]
I wasn't sure if the R&C conversion was ready for review yet, so I didn't take a look.   Feel free to assign back to me for review when you're done.

**Comment by Luisav1** [comment]
Thanks @pixelzoom. I've reverted the renaming commits done above to use the old image filenames. This is now ready for your review.

**Comment by pixelzoom** [comment]
Conversion looks good.

I found a couple of things in area-model-common that were vestigial (GameScreenIcon, JugglerPortrayal), and deleted them in the above commit.  Back to @Luisav1 in case there's anything else that is vestigial that I'm not aware of.  Feel free to close if there's nothing else to do.

**Comment by Luisav1** [comment]
Thanks for tidying up the vestigial items in area-model-common. Sorry for missing those files initially, I found no other vestigial items. Closing.
