### ISSUE TITLE
Background and Foreground colors?

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-multiplication#3]
@jonathanolson demonstrated the latest version of Area Model Multiplication today and I noticed the sim has mostly white components on a white background.  I don't recall any other sims that use the same white on white pattern.  I'm not familiar with the design for the sim, but wanted to check whether that is under discussion.  Having a different color for the area vs the background could help it stand out more.  Assigned to @jonathanolson to evaluate and delegate to the design team.

**Comment by amanda-phet** [comment]
The background is not white at this time so I assume this issue is no longer relevant.
