### ISSUE TITLE
RewardNode should not show variable terms

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-multiplication#4]
The RewardNode from this sim's game shows variable terms ("x" and "x<sup>2</sup>"). It shouldn't since this sim does not use variables.

<img width="1662" alt="screen shot 2018-04-16 at 2 45 40 pm" src="https://user-images.githubusercontent.com/5863899/38834229-0c105e34-4185-11e8-876c-414474b717fa.png">

Seen on macOS 10.13.3 Chrome, master (noon?)

**Comment by jonathanolson** [comment]
Should be fixed in master.

**Comment by phet-steele** [comment]
It's good!
