### ISSUE TITLE
Add Africa, Africa Modest, Asia, Latin America, and Oceania character sets

### ISSUE THREAD

**Issue by Luisav1** [phetsims/area-model-multiplication#8]
First need to add a preference model and then we'll add the classes and structure for the character sets.

**Comment by amanda-phet** [comment]
Artwork is all uploaded. Over to @Luisav1

**Comment by Luisav1** [comment]
The artwork is all integrated now. @amanda-phet could you review to ensure it's all good? Thanks!

**Comment by amanda-phet** [comment]
The icons looked good, but now we're replacing them with the svg images. Let me know when those are ready for review.

**Comment by amanda-phet** [comment]
SVG screen icons are now uploaded.

**Comment by Luisav1** [comment]
All the artwork is now replaced with the svg files. @amanda-phet sending this your way for your review.

**Comment by amanda-phet** [comment]
All of the artwork looks good to me!
